Add missing require for DOMPurify
linagora/esn-frontend-common-libs pull request #245
Opened 2021-11-09 13:10 UTC by alagane

Related to https://github.com/linagora/esn-frontend-mailto/issues/94

2021-11-09 14:39 UTC, fabienmoyon requested changes

2021-11-09 14:39 UTC, fabienmoyon commented on src/frontend/js/modules/core.spec.js
> +  describe.only('The htmlCleaner service', function() {
remove .only

2021-11-09 15:04 UTC, alagane commented
Force-pushed to remove the `.only`

2021-11-09 15:35 UTC, fabienmoyon approved these changes

2021-11-09 17:28 UTC, oubchid approved these changes

2021-11-10 08:18 UTC, renaudboyer approved these changes

2021-11-15 08:40 UTC, merged