esn-frontend-common-libs#73: Bring back missing tests
linagora/esn-frontend-common-libs pull request #91
Opened 2020-08-13 04:54 UTC by billyfrost418

2020-08-13 06:48 UTC, tuanlc submitted a review, later dismissed
Good work :tada: 
I don't see any test in modules that are listed in `/src/modules`. Do they have tests?

2020-08-13 06:59 UTC, itswillta requested changes
> Good work 
> I don't see any test in modules that are listed in `/src/modules`. Do they have tests?

Khanh forgot to bring back those tests. Those are the older tests that lie in this folder: https://github.com/linagora/openpaas-esn/tree/master/test/unit-frontend/modules. You can bring them next to the tested JS files, and remember to suffix them with `.spec.js`.

2020-08-14 08:25 UTC, itswillta approved these changes

2020-08-14 08:52 UTC, tuanlc approved these changes

2020-08-14 08:53 UTC, merged